CREATE TABLE `application_snapshots` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`timestamp` integer NOT NULL,
	`app_name` text NOT NULL,
	`app_display_name` text NOT NULL,
	`total_packets` integer DEFAULT 0 NOT NULL,
	`total_bytes_sent` integer DEFAULT 0 NOT NULL,
	`total_bytes_received` integer DEFAULT 0 NOT NULL,
	`inbound_bytes` integer DEFAULT 0 NOT NULL,
	`outbound_bytes` integer DEFAULT 0 NOT NULL,
	`ipv4_packets` integer DEFAULT 0 NOT NULL,
	`ipv6_packets` integer DEFAULT 0 NOT NULL,
	`tcp_packets` integer DEFAULT 0 NOT NULL,
	`udp_packets` integer DEFAULT 0 NOT NULL,
	`ipv4_percent` integer DEFAULT 0 NOT NULL,
	`ipv6_percent` integer DEFAULT 0 NOT NULL,
	`tcp_percent` integer DEFAULT 0 NOT NULL,
	`udp_percent` integer DEFAULT 0 NOT NULL,
	`process_count` integer DEFAULT 0 NOT NULL,
	`process_registry_ids` text,
	`unique_remote_ips` text,
	`unique_domains` text,
	`geo_locations` text,
	`interface_stats` text,
	`first_seen` integer NOT NULL,
	`last_seen` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `global_snapshots` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`timestamp` integer NOT NULL,
	`interface_name` text NOT NULL,
	`total_packets` integer DEFAULT 0 NOT NULL,
	`total_bytes_sent` integer DEFAULT 0 NOT NULL,
	`total_bytes_recvd` integer DEFAULT 0 NOT NULL,
	`ipv4_packets` integer DEFAULT 0 NOT NULL,
	`ipv6_packets` integer DEFAULT 0 NOT NULL,
	`tcp_packets` integer DEFAULT 0 NOT NULL,
	`udp_packets` integer DEFAULT 0 NOT NULL,
	`ipv4_percent` integer DEFAULT 0 NOT NULL,
	`ipv6_percent` integer DEFAULT 0 NOT NULL,
	`tcp_percent` integer DEFAULT 0 NOT NULL,
	`udp_percent` integer DEFAULT 0 NOT NULL,
	`inbound_bytes` integer DEFAULT 0 NOT NULL,
	`outbound_bytes` integer DEFAULT 0 NOT NULL,
	`first_seen` integer NOT NULL,
	`last_seen` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE `process_snapshots` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`timestamp` integer NOT NULL,
	`process_id` text NOT NULL,
	`app_name` text NOT NULL,
	`pid` integer NOT NULL,
	`parent_pid` integer NOT NULL,
	`proc_name` text NOT NULL,
	`exe_path` text,
	`is_root_process` integer NOT NULL,
	`total_packets` integer DEFAULT 0 NOT NULL,
	`total_bytes_sent` integer DEFAULT 0 NOT NULL,
	`total_bytes_received` integer DEFAULT 0 NOT NULL,
	`inbound_bytes` integer DEFAULT 0 NOT NULL,
	`outbound_bytes` integer DEFAULT 0 NOT NULL,
	`ipv4_packets` integer DEFAULT 0 NOT NULL,
	`ipv6_packets` integer DEFAULT 0 NOT NULL,
	`tcp_packets` integer DEFAULT 0 NOT NULL,
	`udp_packets` integer DEFAULT 0 NOT NULL,
	`ipv4_percent` integer DEFAULT 0 NOT NULL,
	`ipv6_percent` integer DEFAULT 0 NOT NULL,
	`tcp_percent` integer DEFAULT 0 NOT NULL,
	`udp_percent` integer DEFAULT 0 NOT NULL,
	`unique_remote_ips` text,
	`geo_locations` text,
	`interface_stats` text,
	`first_seen` integer NOT NULL,
	`last_seen` integer NOT NULL
);
